### ISSUE TITLE
Make A CLI 

### ISSUE THREAD

**Issue by srsandy** [imsnawaz/MAC-Changer#1]
# CLI
**As a user**, I should not `edit` the code.
Better give me 
A command that like

     mac-change <PASSWORD> <AA:BB:CC:DD:EE:FF>

## +1 
If you are able to mask the password. [*help*](https://stackoverflow.com/questions/6856635/hide-password-input-on-terminal)

## +1 
If are able to host it on
- homebrew
- apt
- DNF
- RMP

**Comment by imsnawaz** [comment]
I intentionally didn't want to make a CLI. I wanted to make it as least interactive as possible.
